#!/bin/bash

# Basic information
curl -H "Content-Type: application/json" -X POST -d '{"user":{"name":"Carlos Domingo", "email":"cdomingo@gmail.com", "password":"Hello1234"}}' http://localhost:3000/users
http POST localhost:3000/places name="Dormitorio"     user_id=1
http POST localhost:3000/lights name="DRMTR_1"    consumption=0 place_id=1

# Light logs
#http POST localhost:3000/light_logs event="on"  light_id=1
#sleep 30
#http POST localhost:3000/light_logs event="off" light_id=1
#sleep 30
#http POST localhost:3000/light_logs event="on"  light_id=1
#sleep 30
#http POST localhost:3000/light_logs event="off" light_id=1
#sleep 30
#http POST localhost:3000/light_logs event="on"  light_id=1
#sleep 30
#http POST localhost:3000/light_logs event="off" light_id=1
#sleep 30
#http POST localhost:3000/light_logs event="on"  light_id=1
#sleep 30
#http POST localhost:3000/light_logs event="off" light_id=1
#sleep 30
#http POST localhost:3000/light_logs event="on"  light_id=1
#sleep 30
#http POST localhost:3000/light_logs event="off" light_id=1