#!/bin/bash

# db:localhost

# create user
#curl -H "Content-Type: application/json" -X POST -d '{"user":{"name":"Lina Palacios", "email":"lpalacios@gmail.com", "password":"Hello1234"}}' http://localhost:3000/users

# login user
#curl -X POST --data "email=lpalacios@gmail.com&password=Hello1234" http://localhost:3000/login.json

# logout user
#curl -X DELETE -H "Authorization: Token token=9iVY71ofurt7N7jYHkGu1X79" http://localhost:3000/logout.json

# Carlos Domingo - Apartamento de una habitacion
curl -H "Content-Type: application/json" -X POST -d '{"user":{"name":"Carlos Domingo", "email":"cdomingo@gmail.com", "password":"Hello1234"}}' http://localhost:3000/users

# Places
http POST localhost:3000/places name="Dormitorio" user_id=1
http POST localhost:3000/places name="Sala-Comedor" user_id=1
http POST localhost:3000/places name="Cocina" user_id=1
http POST localhost:3000/places name="Zona de lavado" user_id=1
http POST localhost:3000/places name="Baño" user_id=1

# Lights
http POST localhost:3000/lights name="DRMTR_1" consumption=0 place_id=1
http POST localhost:3000/lights name="DRMTR_2" consumption=0 place_id=1
http POST localhost:3000/lights name="SL_CMDR_1" consumption=0 place_id=2
http POST localhost:3000/lights name="SL_CMDR_2" consumption=0 place_id=2
http POST localhost:3000/lights name="SLC_MDR_3" consumption=0 place_id=2
http POST localhost:3000/lights name="CCN_1" consumption=0 place_id=3
http POST localhost:3000/lights name="CCN_2" consumption=0 place_id=3
http POST localhost:3000/lights name="ZN_D_LVD_1" consumption=0 place_id=4
http POST localhost:3000/lights name="BÑ_1" consumption=0 place_id=5

# Schedule_times
http POST localhost:3000/schedule_times set_to=true event_time='2017-10-05 03:14:00' light_id=1
http POST localhost:3000/schedule_times set_to=false event_time='2017-10-05 04:14:00' light_id=1
http POST localhost:3000/schedule_times set_to=true event_time='2017-10-05 06:30:00' light_id=1
http POST localhost:3000/schedule_times set_to=false event_time='2017-10-05 10:05:00' light_id=1

http POST localhost:3000/schedule_times set_to=true event_time='2017-10-05 05:14:00' light_id=2
http POST localhost:3000/schedule_times set_to=false event_time='2017-10-05 09:14:00' light_id=2
http POST localhost:3000/schedule_times set_to=true event_time='2017-10-05 12:30:00' light_id=2
http POST localhost:3000/schedule_times set_to=false event_time='2017-10-05 23:05:00' light_id=2

# Light_logs
http POST localhost:3000/light_logs event="off" light_id=1
http POST localhost:3000/light_logs event="on" light_id=1
http POST localhost:3000/light_logs event="off" light_id=1
http POST localhost:3000/light_logs event="on" light_id=1
http POST localhost:3000/light_logs event="off" light_id=1
http POST localhost:3000/light_logs event="on" light_id=1
http POST localhost:3000/light_logs event="off" light_id=1
http POST localhost:3000/light_logs event="on" light_id=1
http POST localhost:3000/light_logs event="off" light_id=1
http POST localhost:3000/light_logs event="on" light_id=1
http POST localhost:3000/light_logs event="off" light_id=1

http POST localhost:3000/light_logs event="off" light_id=2
http POST localhost:3000/light_logs event="on" light_id=2
http POST localhost:3000/light_logs event="off" light_id=2
http POST localhost:3000/light_logs event="on" light_id=2
http POST localhost:3000/light_logs event="off" light_id=2
http POST localhost:3000/light_logs event="on" light_id=2

http POST localhost:3000/light_logs event="off" light_id=3
http POST localhost:3000/light_logs event="off" light_id=4
http POST localhost:3000/light_logs event="off" light_id=5
http POST localhost:3000/light_logs event="off" light_id=6
http POST localhost:3000/light_logs event="off" light_id=7
http POST localhost:3000/light_logs event="off" light_id=8
http POST localhost:3000/light_logs event="off" light_id=9

# Ernesto Arango - Apartamento de dos habitaciones
#curl -H "Content-Type: application/json" -X POST -d '{"user":{"name":"Ernesto Arango", "email":"earango@gmail.com", "password":"123123"}}' http://localhost:3000/users
#http POST localhost:3000/places name="Habitación principal" user_id=2
#http POST localhost:3000/places name="Habitación secundaria" user_id=2
#http POST localhost:3000/places name="Sala-Comedor" user_id=2
#http POST localhost:3000/places name="Cocina" user_id=2
#http POST localhost:3000/places name="Zona de ropa" user_id=2
#http POST localhost:3000/places name="Baño" user_id=2
#http POST localhost:3000/lights name="HBTCN_PRNCPL_1" consumption=0 place_id=6
#http POST localhost:3000/lights name="HBTCN_PRNCPL_2" consumption=0 place_id=6
#http POST localhost:3000/lights name="HBTCN_SCNDR_1" consumption=0 place_id=7
#http POST localhost:3000/lights name="SL_CMDR_1" consumption=0 place_id=8
#http POST localhost:3000/lights name="SL_CMDR_2" consumption=0 place_id=8
#http POST localhost:3000/lights name="SL_CMDR_3" consumption=0 place_id=8
#http POST localhost:3000/lights name="CCN_1" consumption=0 place_id=9
#http POST localhost:3000/lights name="CCN_2" consumption=0 place_id=9
#http POST localhost:3000/lights name="ZN_D_RP_1" consumption=0 place_id=10
#http POST localhost:3000/lights name="BÑ_1" consumption=0 place_id=11

#http POST localhost:3000/light_logs event="off" light_id=10
#http POST localhost:3000/light_logs event="off" light_id=11
#http POST localhost:3000/light_logs event="off" light_id=12
#http POST localhost:3000/light_logs event="off" light_id=13
#http POST localhost:3000/light_logs event="off" light_id=14
#http POST localhost:3000/light_logs event="off" light_id=15
#http POST localhost:3000/light_logs event="off" light_id=16
#http POST localhost:3000/light_logs event="off" light_id=17
#http POST localhost:3000/light_logs event="off" light_id=18
#http POST localhost:3000/light_logs event="off" light_id=19

# Ximena Perez - Casa de tres habitaciones
#curl -H "Content-Type: application/json" -X POST -d '{"user":{"name":"Ximena Perez", "email":"xperez@gmail.com", "password":"password"}}' http://localhost:3000/users
#http POST localhost:3000/places name="Habitación principal" user_id=3 #12
#http POST localhost:3000/places name="Habitación secundaria" user_id=3 #13
#http POST localhost:3000/places name="Habitación huesped" user_id=3 #14
#http POST localhost:3000/places name="Sala-Comedor" user_id=3 #15
#http POST localhost:3000/places name="Cocina" user_id=3 #16
#http POST localhost:3000/places name="Zona de ropa" user_id=3 #17
#http POST localhost:3000/places name="Baño" user_id=3 #18
#http POST localhost:3000/lights name="HBTCN_PRNCPL_1" consumption=0 place_id=12
#http POST localhost:3000/lights name="HBTCN_PRNCPL_2" consumption=0 place_id=12
#http POST localhost:3000/lights name="HBTCN_SCNDR_1" consumption=0 place_id=13
#http POST localhost:3000/lights name="HBTCN_SCNDR_2" consumption=0 place_id=13
#http POST localhost:3000/lights name="HBTCN_HSPD_1" consumption=0 place_id=14
#http POST localhost:3000/lights name="SL_CMDR_1" consumption=0 place_id=15
#http POST localhost:3000/lights name="SL_CMDR_2" consumption=0 place_id=15
#http POST localhost:3000/lights name="SL_CMDR_3" consumption=0 place_id=15
#http POST localhost:3000/lights name="CCN_1" consumption=0 place_id=16
#http POST localhost:3000/lights name="CCN_2" consumption=0 place_id=16
#http POST localhost:3000/lights name="ZN_D_RP_1" consumption=0 place_id=17
#http POST localhost:3000/lights name="BÑ_1" consumption=0 place_id=18

#http POST localhost:3000/light_logs event="off" light_id=20
#http POST localhost:3000/light_logs event="off" light_id=21
#http POST localhost:3000/light_logs event="off" light_id=22
#http POST localhost:3000/light_logs event="off" light_id=23
#http POST localhost:3000/light_logs event="off" light_id=24
#http POST localhost:3000/light_logs event="off" light_id=25
#http POST localhost:3000/light_logs event="off" light_id=26
#http POST localhost:3000/light_logs event="off" light_id=27
#http POST localhost:3000/light_logs event="off" light_id=28
#http POST localhost:3000/light_logs event="off" light_id=29
#http POST localhost:3000/light_logs event="off" light_id=30
#http POST localhost:3000/light_logs event="off" light_id=31

#Call db/seed.rb to update light_logs registers to created_at dates that gives us some ligth consumption
#rake db:seed
