#!/bin/bash
# db:localhost
# create user
#curl -H "Content-Type: application/json" -X POST -d '{"user":{"name":"Lina Palacios", "email":"lpalacios@gmail.com", "password":"Hello1234"}}' http://192.168.99.101:3000/users

# login user
#curl -X POST --data "email=lpalacios@gmail.com&password=Hello1234" http://192.168.99.101:3000/login.json

# logout user
#curl -X DELETE -H "Authorization: Token token=9iVY71ofurt7N7jYHkGu1X79" http://192.168.99.101:3000/logout.json

# Carlos Domingo - Apartamento de una habitacion
curl -H "Content-Type: application/json" -X POST -d '{"user":{"name":"Carlos Domingo", "email":"cdomingo@gmail.com", "password":"Hello1234"}}' http://192.168.99.101:3000/users
http POST 192.168.99.101:3000/places name="Dormitorio" user_id=1
http POST 192.168.99.101:3000/places name="Sala-Comedor" user_id=1
http POST 192.168.99.101:3000/places name="Cocina" user_id=1
http POST 192.168.99.101:3000/places name="Zona de lavado" user_id=1
http POST 192.168.99.101:3000/places name="Baño" user_id=1
http POST 192.168.99.101:3000/lights name="DRMTR_1" consumption=10 place_id=1
http POST 192.168.99.101:3000/lights name="DRMTR_2" consumption=10 place_id=1
http POST 192.168.99.101:3000/lights name="SL_CMDR_1" consumption=10 place_id=2
http POST 192.168.99.101:3000/lights name="SL_CMDR_2" consumption=10 place_id=2
http POST 192.168.99.101:3000/lights name="SLC_MDR_3" consumption=10 place_id=2
http POST 192.168.99.101:3000/lights name="CCN_1" consumption=10 place_id=3
http POST 192.168.99.101:3000/lights name="CCN_2" consumption=10 place_id=3
http POST 192.168.99.101:3000/lights name="ZN_D_LVD_1" consumption=10 place_id=4
http POST 192.168.99.101:3000/lights name="BÑ_1" consumption=10 place_id=5

# Ernesto Arango - Apartamento de dos habitaciones
curl -H "Content-Type: application/json" -X POST -d '{"user":{"name":"Ernesto Arango", "email":"earango@gmail.com", "password":"123123"}}' http://192.168.99.101:3000/users
http POST 192.168.99.101:3000/places name="Habitación principal" user_id=2
http POST 192.168.99.101:3000/places name="Habitación secundaria" user_id=2
http POST 192.168.99.101:3000/places name="Sala-Comedor" user_id=2
http POST 192.168.99.101:3000/places name="Cocina" user_id=2
http POST 192.168.99.101:3000/places name="Zona de ropa" user_id=2
http POST 192.168.99.101:3000/places name="Baño" user_id=2
http POST 192.168.99.101:3000/lights name="HBTCN_PRNCPL_1" consumption=10 place_id=6
http POST 192.168.99.101:3000/lights name="HBTCN_PRNCPL_2" consumption=10 place_id=6
http POST 192.168.99.101:3000/lights name="HBTCN_SCNDR_1" consumption=10 place_id=7
http POST 192.168.99.101:3000/lights name="SL_CMDR_1" consumption=10 place_id=8
http POST 192.168.99.101:3000/lights name="SL_CMDR_2" consumption=10 place_id=8
http POST 192.168.99.101:3000/lights name="SL_CMDR_3" consumption=10 place_id=8
http POST 192.168.99.101:3000/lights name="CCN_1" consumption=10 place_id=9
http POST 192.168.99.101:3000/lights name="CCN_2" consumption=10 place_id=9
http POST 192.168.99.101:3000/lights name="ZN_D_RP_1" consumption=10 place_id=10
http POST 192.168.99.101:3000/lights name="BÑ_1" consumption=10 place_id=11

# Ximena Perez - Casa de tres habitaciones
curl -H "Content-Type: application/json" -X POST -d '{"user":{"name":"Ximena Perez", "email":"xperez@gmail.com", "password":"password"}}' http://192.168.99.101:3000/users
http POST 192.168.99.101:3000/places name="Habitación principal" user_id=3 #12
http POST 192.168.99.101:3000/places name="Habitación secundaria" user_id=3 #13
http POST 192.168.99.101:3000/places name="Habitación huesped" user_id=3 #14
http POST 192.168.99.101:3000/places name="Sala-Comedor" user_id=3 #15
http POST 192.168.99.101:3000/places name="Cocina" user_id=3 #16
http POST 192.168.99.101:3000/places name="Zona de ropa" user_id=3 #17
http POST 192.168.99.101:3000/places name="Baño" user_id=3 #18
http POST 192.168.99.101:3000/lights name="HBTCN_PRNCPL_1" consumption=10 place_id=12
http POST 192.168.99.101:3000/lights name="HBTCN_PRNCPL_2" consumption=10 place_id=12
http POST 192.168.99.101:3000/lights name="HBTCN_SCNDR_1" consumption=10 place_id=13
http POST 192.168.99.101:3000/lights name="HBTCN_SCNDR_2" consumption=10 place_id=13
http POST 192.168.99.101:3000/lights name="HBTCN_HSPD_1" consumption=10 place_id=14
http POST 192.168.99.101:3000/lights name="SL_CMDR_1" consumption=10 place_id=15
http POST 192.168.99.101:3000/lights name="SL_CMDR_2" consumption=10 place_id=15
http POST 192.168.99.101:3000/lights name="SL_CMDR_3" consumption=10 place_id=15
http POST 192.168.99.101:3000/lights name="CCN_1" consumption=10 place_id=16
http POST 192.168.99.101:3000/lights name="CCN_2" consumption=10 place_id=16
http POST 192.168.99.101:3000/lights name="ZN_D_RP_1" consumption=10 place_id=17
http POST 192.168.99.101:3000/lights name="BÑ_1" consumption=10 place_id=18
