#!/bin/bash
eval $(docker-machine env rancher-node1) # Remove unused docker containers
docker images --no-trunc| grep none | awk '{print $3}' | xargs -r docker rmi
docker images --no-trunc| grep none | awk '{print $3}' | xargs -r docker rmi