#!/bin/bash
# Database initialization script

# Post notes: create, login and logout of a user
#curl -H "Content-Type: application/json" -X POST -d '{"user":{"name":"Lina Palacios", "email":"lpalacios@unal.edu.co", "password":"123456"}}' http://localhost:3000/users
#curl -X POST --data "email=lpalacios@gmail.com&password=123456" http://localhost:3000/login.json
#curl -X DELETE -H "Authorization: Token token=9iVY71ofurt7N7jYHkGu1X79" http://localhost:3000/logout.json

backend_path="" # Backend web path
if [ $# -eq 0 ]; then # Check options existence
  echo "No arguments supplied"; exit 1
elif [ $# -gt 1 ]; then # Check options number
  echo "The number of option is greater than 1"
elif [ $1 = "-l" ]; then # Post on localhost
  echo "Localhost option selected"
  backend_path="localhost:3000"
elif [ $1 = "-d" ]; then # Post on docker
  echo "Docker option selected"
  backend_path="192.168.99.101:3000"
else # Error message
  echo "Argument not allowed"; exit 1
fi

# Carlos Domingo - Apartment with one room
curl -H "Content-Type: application/json" -X POST -d '{"user":{"name":"Carlos Domingo", "email":"cdomingo@unal.edu.co", "password":"123123123"}}' http://10.203.139.159:3000/users
http POST http://10.203.139.159:3000/places name="Dormitorio" user_id=1
http POST $backend_path/places name="Sala-Comedor" user_id=1
http POST $backend_path/places name="Cocina" user_id=1
http POST $backend_path/places name="Zona de lavado" user_id=1
http POST $backend_path/places name="Baño" user_id=1
http POST $backend_path/lights name="DRMTR_1" consumption=0 place_id=1
http POST $backend_path/lights name="DRMTR_2" consumption=0 place_id=1
http POST $backend_path/lights name="SL_CMDR_1" consumption=0 place_id=2
http POST $backend_path/lights name="SL_CMDR_2" consumption=0 place_id=2
http POST $backend_path/lights name="SLC_MDR_3" consumption=0 place_id=2
http POST $backend_path/lights name="CCN_1" consumption=0 place_id=3
http POST $backend_path/lights name="CCN_2" consumption=0 place_id=3
http POST $backend_path/lights name="ZN_D_LVD_1" consumption=0 place_id=4
http POST $backend_path/lights name="BÑ_1" consumption=0 place_id=5

# Ernesto Arango - Apartment with two rooms
#curl -H "Content-Type: application/json" -X POST -d '{"user":{"name":"Ernesto Arango", "email":"earango@gmail.com", "password":"123123"}}' http://$backend_path/users
#http POST $backend_path/places name="Habitación principal" user_id=2
#http POST $backend_path/places name="Habitación secundaria" user_id=2
#http POST $backend_path/places name="Sala-Comedor" user_id=2
#http POST $backend_path/places name="Cocina" user_id=2
#http POST $backend_path/places name="Zona de ropa" user_id=2
#http POST $backend_path/places name="Baño" user_id=2
#http POST $backend_path/lights name="HBTCN_PRNCPL_1" consumption=0 place_id=6
#http POST $backend_path/lights name="HBTCN_PRNCPL_2" consumption=0 place_id=6
#http POST $backend_path/lights name="HBTCN_SCNDR_1" consumption=0 place_id=7
#http POST $backend_path/lights name="SL_CMDR_1" consumption=0 place_id=8
#http POST $backend_path/lights name="SL_CMDR_2" consumption=0 place_id=8
#http POST $backend_path/lights name="SL_CMDR_3" consumption=0 place_id=8
#http POST $backend_path/lights name="CCN_1" consumption=0 place_id=9
#http POST $backend_path/lights name="CCN_2" consumption=0 place_id=9
#http POST $backend_path/lights name="ZN_D_RP_1" consumption=0 place_id=10
#http POST $backend_path/lights name="BÑ_1" consumption=0 place_id=11

# Ximena Perez - House with three rooms
#curl -H "Content-Type: application/json" -X POST -d '{"user":{"name":"Ximena Perez", "email":"xperez@gmail.com", "password":"password"}}' http://$backend_path/users
#http POST $backend_path/places name="Habitación principal" user_id=3
#http POST $backend_path/places name="Habitación secundaria" user_id=3
#http POST $backend_path/places name="Habitación huesped" user_id=3
#http POST $backend_path/places name="Sala-Comedor" user_id=3
#http POST $backend_path/places name="Cocina" user_id=3
#http POST $backend_path/places name="Zona de ropa" user_id=3
#http POST $backend_path/places name="Baño" user_id=3
#http POST $backend_path/lights name="HBTCN_PRNCPL_1" consumption=0 place_id=12
#http POST $backend_path/lights name="HBTCN_PRNCPL_2" consumption=0 place_id=12
#http POST $backend_path/lights name="HBTCN_SCNDR_1" consumption=0 place_id=13
#http POST $backend_path/lights name="HBTCN_SCNDR_2" consumption=0 place_id=13
#http POST $backend_path/lights name="HBTCN_HSPD_1" consumption=0 place_id=14
#http POST $backend_path/lights name="SL_CMDR_1" consumption=0 place_id=15
#http POST $backend_path/lights name="SL_CMDR_2" consumption=0 place_id=15
#http POST $backend_path/lights name="SL_CMDR_3" consumption=0 place_id=15
#http POST $backend_path/lights name="CCN_1" consumption=0 place_id=16
#http POST $backend_path/lights name="CCN_2" consumption=0 place_id=16
#http POST $backend_path/lights name="ZN_D_RP_1" consumption=0 place_id=17
#http POST $backend_path/lights name="BÑ_1" consumption=0 place_id=18